[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200

lib_deps = 
    kosme/arduinoFFT@^2.0.4
    https://github.com/adafruit/Adafruit_ADS1X15.git

; --- ESP32 DevKit ---
[env:esp32dev]
board = esp32dev
build_flags = 
    -I include
    -D BOARD_ESP32_DEV

; --- Seeed XIAO ESP32-C6 ---
[env:seeed_xiao_esp32c6]
board = seeed_xiao_esp32c6
build_flags = 
    -I include
    -D BOARD_XIAO_ESP32C6